CREATE TABLE USER_AP(
ID NUMBER,
CONSTRAINT USER_ID_PK PRIMARY KEY (ID),
USER_NAME NVARCHAR2(50) NOT NULL,
PASSWORD NVARCHAR2(50) NOT NULL,
COUNTRY NVARCHAR2(50),
USER_TYPE NVARCHAR2(50),
CONSTRAINT USER_TYPE_CH CHECK(USER_TYPE IN('ADMIN','USER')),
LOGIN_STATUS NUMBER(1),
CONSTRAINT LOGIN_STATUS_CH CHECK(LOGIN_STATUS IN(0,1))
ORDER_ID NUMBER,
CONSTRAINT ORDER_BK_FK FOREIGN KEY(ID) REFERENCES ORDERS_BK(ID)ON DELETE SET NULL
);

ALTER TABLE USER_AP
ADD CONSTRAINT ORDER_BK_FK FOREIGN KEY(ID) REFERENCES ORDERS_BK(ID)ON DELETE SET NULL;