CREATE TABLE ORDERS_BK(
ID NUMBER,
CONSTRAINT ORDER_ID_PK PRIMARY KEY (ID),
USER_ID NUMBER,
CONSTRAINT USER_BK_FK FOREIGN KEY(USER_ID) REFERENCES USER_AP(ID),
ROOM_ID NUMBER,
CONSTRAINT ROOM_BK_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ID) ON DELETE SET NULL,
ORDER_DATE_FROM DATE,
ORDER_DATE_TO DATE,
MONEY_PAID NUMBER(10,2)
)